### ISSUE TITLE
Adding metadata to credential

### ISSUE THREAD

**Issue by accozzam** [spruceid/didkit-python#10]
How can I add metadata to a credential? If I try to add a field, I get: "didkit.DIDKitException: Expansion failed: Expansion failed: Key expansion failed"

**Comment by sbihel** [comment]
Any field needs to be defined in the context. You can either use an existing context or define your own fields like so
```
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        {
          "@protected": true,
          "MyField": "myscheme:MyField",
        }
      ]
```
You can learn more about JSON-LD here https://json-ld.org/.

Please note that it is not possible at this time to provide custom context files, related issue: https://github.com/spruceid/didkit-python/issues/7
