### ISSUE TITLE
The latest published version v0.3.2 for didkit-python is incompatible with Python3.12 and ARM64

### ISSUE THREAD

**Issue by GlugovGrGlib** [spruceid/didkit-python#13]
### Description
During the upgrade to python 3.12 we faced an issue with didkit v0.3.2 as it currently doesn't support nor Python3.12 nor Linux/ARM64 for the python above 3.8 version. All available published wheels can be seen at https://pypi.org/project/didkit/#files.

### Testing instructions
Python3.12 - linux/amd64
```
$ docker run --rm --platform linux/amd64 amd64/python:3.12 bash -c "pip install didkit==0.3.2"
ERROR: Could not find a version that satisfies the requirement didkit==0.3.2 (from versions: 0.0.1, 0.2.1)
ERROR: No matching distribution found for didkit==0.3.2
```

Python3.11 - linux/arm64
```
$ docker run arm64v8/python:3.11 bash -c "pip install didkit==0.3.2"
ERROR: Could not find a version that satisfies the requirement didkit==0.3.2 (from versions: 0.0.1, 0.2.1)
ERROR: No matching distribution found for didkit==0.3.2
```

### Additional information
There are couple of related issues were created in Open edX repositories which uses didkit-python as dependency
[Python3.12 build failure](https://www.github.com/overhangio/tutor-credentials/issues/34)
[ARM64 build failed](https://www.github.com/openedx/credentials/issues/2477)

**Comment by GlugovGrGlib** [comment]
Hello @sbihel @clehner!
Would you be able to look into this problem?

**Comment by GlugovGrGlib** [comment]
Hi @sbihel, thank you, this fixed an issue for python 3.12, however there's no published packages for manylinux ARM64 for any version of python latter than py3.8

**Comment by sbihel** [comment]
I see. I'm sorry I don't have time to look more into manylinux and what to do to compile for all python versions. We had to [pin the cross-compilation python version](https://github.com/spruceid/didkit-python/blob/de7f94620915ea2df3a615b33462e1cbf38abfe3/.github/workflows/release.yml#L62) and I don't know if there's now a better way to do it.

**Comment by GlugovGrGlib** [comment]
@sbihel it seems like removing [PYO3_CROSS_LIB_DIR](https://github.com/spruceid/didkit-python/blob/main/.github/workflows/release.yml#L59) env variable from the Linux CD step enables ARM wheel builds for py3.9-py3.11. Probably Maturin now can auto-resolve correct version to use. 
I tested this in a fork, and [it worked fine](https://github.com/GlugovGrGlib/didkit-python/actions/runs/10394530610).
Do you think this change to CD is feasible as a temporary solution to publish ARM64 versions of the package up to Python 3.11, and latter try to figure out what changes are necessary to enable py3.12 arm64 builds?

**Comment by sbihel** [comment]
Looks like Python 3.12 is covered as well https://github.com/GlugovGrGlib/didkit-python/actions/runs/10394530610/job/28784522217#step:4:22.

Thanks a lot for testing this!! `v0.3.3` is currently being published, hopefully we should be able to close this issue.

**Comment by GlugovGrGlib** [comment]
I've tested v0.3.3, and it is working as expected now with python3.12 for both architectures ARM64 and AMD64.
Thank you for your support, I will close the issue as resolved.
